### ISSUE TITLE
fixed?

### ISSUE THREAD

**Issue by valentinorusconi** [openjck/bug-demo-react-chartjs-2-mutates-state#1]
you know a way how this can be fixed? I'm struggling with the same atm.

**Comment by openjck** [comment]
Yes! We worked around it [like this](https://github.com/mozilla/firefox-test-tube/blob/2207b8db0657c2482c14734b839c8ff977702934/src/components/containers/ChartContainer.js#L244-L246).

Basically, if you are passing a `data` variable to react-chartjs-2, do this first:

```js
data = JSON.parse(JSON.stringify(data));
```
